namespace IALClient.Infra.ExternalApi.Dto.Main;

public record DealerResponseDto(

    string GroupCD,
    string CompanyCD,
    string BranchCD,
    string Code,
    string Desc,
    string Company,
    string Add1,
    string Add2,
    string Add3,
    string AreaCD,
    string City,
    string Tel,
    string Cel,
    string Email,
    string CKNo,
    string VATNo,
    bool Closed,
    string Province,
    string TelC,
    string TelA,
    float Longitude,
    float Latitude,
    string Contact,
    string Contcelc,
    string Contcela,
    string Contcel,
    string Contemail,
    string Day1s,
    string Day1e,
    string Day2s,
    string Day2e,
    string Day3s,
    string Day3e,
    string Day4s,
    string Day4e,
    string Day5s,
    string Day5e,
    string Day6s,
    string Day6e,
    string Day7s,
    string Day7e,
    string Dayxs,
    string Dayxe
);


