name: Deploy .NET 8 App to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and test with .NET
        run: dotnet build --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish -c Release -o out

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ialclient:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ialclient:${{ github.sha }}

      - name: Deploy Docker image to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-147-165-133.compute-1.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ialclient:${{ github.sha }}
            docker stop ialclient || true
            docker rm ialclient || true
            docker run -d -p 8080:8080 --name ialclient ${{ secrets.DOCKER_HUB_USERNAME }}/ialclient:${{ github.sha }}        
          
